In [1]:
from numpy import *

In [3]:
randMat = mat(random.rand(4,4))

In [6]:
randMatI = randMat.I

In [7]:
multiplied = randMat * randMatI

In [8]:
print(multiplied)

[[  1.00000000e+00  -4.44089210e-16   0.00000000e+00   0.00000000e+00]
 [ -2.22044605e-16   1.00000000e+00   0.00000000e+00   2.22044605e-16]
 [ -1.11022302e-15   2.22044605e-16   1.00000000e+00   1.11022302e-16]
 [  2.77555756e-16  -8.32667268e-16  -1.11022302e-16   1.00000000e+00]]
